export const bbqTable = [
  { id: 1, name: "Normales Tragwerk (50 Jahre Nutzungsdauer)", value: "N" },
  { id: 2, name: "Abweichende Nutzungsdauer", value: "S" },
  { id: 3, name: "LAU / HBV Anlagen (WHG)", value: "E" },
  { id: 4, name: "JGS Anlagen", value: "E" },
  { id: 6, name: "Ingenieurbauwerke Verkehrsträger", value: "S" },
  { id: 7, name: "Windenergieanlagen", value: "E" },
  { id: 8, name: "Maschinenfundamente / Kranbahnen", value: "E" },
  { id: 9, name: "Sichtbeton SB1", value: "N" },
  { id: 10, name: "Sichtbeton SB2–SB4", value: "S" },
  { id: 16, name: "LP-Beton XF2/XF3/XF4", value: "E" },
  { id: 17, name: "XF2/XF3 ohne Luftporen", value: "E" },
  { id: 18, name: "chemischer Angriff XA2", value: "E" },
  { id: 19, name: "chemischer Angriff XA3", value: "S" },
  { id: 27, name: "Beton mit zusätzlichen Planungsanforderungen", value: "S" },
  { id: 32, name: "Leichtbeton", value: "E" },
  { id: 33, name: "Schwerbeton", value: "S" },
  { id: 36, name: "Selbstverdichtender Beton", value: "E" },
  { id: 42, name: "Unterwasserbeton", value: "E" },
  { id: 50, name: "Massige Bauteile", value: "E" },
  { id: 52, name: "WU Konstruktion BK1", value: "E" },
  { id: 53, name: "WU Konstruktion BK2", value: "E" },
  { id: 66, name: "Gleitbauverfahren", value: "S" },
  { id: 67, name: "Frischbetontemperatur >30°C", value: "S" },
  { id: 68, name: "besondere Förderverfahren", value: "S" },
];
